In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv("/Users/rupeshphyaulimagar/Data/Recommendation system/tmdb_5000_movies.csv")

In [3]:
df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [5]:
data = df[['genres','id','title','overview','tagline','keywords']]

In [6]:
data.head(2)

,genres,id,title,overview,tagline,keywords
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."

<br>

<h1>EDA</h1>

In [7]:
data.isnull().sum()

genres        0
id            0
title         0
overview      3
tagline     844
keywords      0
dtype: int64

In [8]:
data.shape

(4803, 6)

In [9]:
data['tagline'] = data['tagline'].fillna('')
data['overview'] = data['overview'].fillna('')

/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/1461127674.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tagline'] = data['tagline'].fillna('')
/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/1461127674.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['overview'] = data['overview'].fillna('')

In [10]:
data.duplicated().sum()

np.int64(0)

In [11]:
 data.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

<br>

<h1>Creating list of each row form Dictionaries [name] </h1>

In [12]:
import ast

In [13]:
 def convert(obj):
     l=[]
     for i in ast.literal_eval(obj):
         l.append(i['name'])
     return l

In [14]:
data['genres'] = data['genres'].apply(convert)

/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/633910978.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['genres'] = data['genres'].apply(convert)

In [15]:
data['keywords'] = data['keywords'].apply(convert)

/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/390802313.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['keywords'] = data['keywords'].apply(convert)

In [16]:
data.head(2)

,genres,id,title,overview,tagline,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","[ocean, drug abuse, exotic island, east india ..."

<h2>Create overview and keywords into list futhter operation</h2>

In [17]:
data['overview'] = data['overview'].apply(lambda x: x.split())

/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/4066898622.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['overview'] = data['overview'].apply(lambda x: x.split())

In [18]:
data['tagline'] = data['tagline'].apply (lambda x: x.split())

/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/4064189261.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tagline'] = data['tagline'].apply (lambda x: x.split())

In [19]:
data.head(2)

,genres,id,title,overview,tagline,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Enter, the, World, of, Pandora.]","[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[At, the, end, of, the, world,, the, adventure...","[ocean, drug abuse, exotic island, east india ..."

<br>

<h2>Removing space  and creating lower case and concanent it for proper tag </h2>

<h3>Removing space</h3>

In [20]:
data['genres'] = data['genres'].apply(lambda x :[i.replace(" ","") for i in x])
data['overview'] = data['overview'].apply(lambda x :[i.replace(" ","") for i in x])
data['tagline'] = data['tagline'].apply(lambda x :[i.replace(" ","") for i in x])
data['keywors'] = data['keywords'].apply(lambda x :[i.replace(" ","") for i in x])

/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/1740999212.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['genres'] = data['genres'].apply(lambda x :[i.replace(" ","") for i in x])
/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/1740999212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['overview'] = data['overview'].apply(lambda x :[i.replace(" ","") for i in x])
/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/1740999212.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tagline'] = data['tagline'].apply(lambda x :[i.replace(" ","") for i in x])
/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/1740999212.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['keywors'] = data['keywords'].apply(lambda x :[i.replace(" ","") for i in x])

<h3>Concatenate at tag (new columns)</h3>

In [21]:
data['tag'] = data['genres'] + data['tagline'] + data['overview'] + data['keywords']

/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/832088204.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tag'] = data['genres'] + data['tagline'] + data['overview'] + data['keywords']

In [22]:
movies = data[['id','title','tag']]

In [23]:
movies.head(2)

,id,title,tag
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, E..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, At, the, end, of,..."

<h3>list into string</h3>

In [24]:
movies['tag'] = movies['tag'].apply(lambda x :" ".join(x))

/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/1695074155.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tag'] = movies['tag'].apply(lambda x :" ".join(x))

<h3>Lower string</h3>

In [25]:
movies['tag'] = movies['tag'].apply(lambda x : x.lower())

/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/634190484.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tag'] = movies['tag'].apply(lambda x : x.lower())

In [26]:
movies.iloc[0].tag

'action adventure fantasy sciencefiction enter the world of pandora. in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d'

<br>

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,stop_words = 'english')

In [28]:
vectors= cv.fit_transform(movies['tag']).toarray()

In [30]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4803, 5000))

In [40]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'],
      shape=(5000,), dtype=object)

In [41]:
import nltk

In [44]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [45]:
def stem(txt):
    y=[]
    for i in txt.split():
       y.append(ps.stem(i))
    return " ".join(y)

In [46]:
movies['tag'] = movies['tag'].apply(stem)

/var/folders/ny/f0k_59013hgbh6fwt58mwm5r0000gn/T/ipykernel_15521/3412586131.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tag'] = movies['tag'].apply(stem)

In [47]:
movies.head(2)

,id,title,tag
0,19995,Avatar,action adventur fantasi sciencefict enter the ...
1,285,Pirates of the Caribbean: At World's End,adventur fantasi action at the end of the worl...